/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Errores;
import Modelo.Medico;
import Modelo.ObtenerDatos;
import Modelo.Principal;
import com.aeat.valida.Validador;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio
 */
public class AltaMedico extends javax.swing.JPanel {

    //Atributos para recoger la informacion
    String codigoCompañia;
    String nombre;
    String codigo;
    String precioHora;
    String Nif;
    Date fechaElegida;
    
    ObtenerDatos objetoObtenerDatos = new ObtenerDatos(); //Objeto para acceder a la clase del paquete Modelo
    
    public AltaMedico(String codigo) {
        initComponents();
        
        codigoCompañia = codigo;
        
        campoCompañia.setText(codigoCompañia);
        campoCompañia.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        campoNif = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoCompañia = new javax.swing.JTextField();
        campoPrecioHora = new javax.swing.JTextField();
        jDatePicker1 = new org.jdatepicker.JDatePicker();
        jLabel7 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        jLabel1.setText("CODIGO");

        jLabel2.setText("NIF");

        jLabel3.setText("ID DE COMPAÑIA");

        jLabel4.setText("NOMBRE");

        jLabel5.setText("FECHA");

        jLabel6.setText("PRECIO/HORA");

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        jDatePicker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePicker1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ALTA MEDICO");

        botonCancelar.setText("CANCELAR");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("ACEPTAR");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoCodigo)
                    .addComponent(campoNif)
                    .addComponent(campoNombre)
                    .addComponent(campoCompañia)
                    .addComponent(campoPrecioHora))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(botonCancelar)
                        .addGap(154, 154, 154)
                        .addComponent(botonAceptar)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        boolean campoBlanco, codigoErroneo;
        if (campoBlanco = comprobarCampos()) //Primero se comprueba que no haya campos en blanco
            JOptionPane.showMessageDialog(null, "Rellene todos los campos" ,"Campos vacios", JOptionPane.ERROR_MESSAGE);
        else
            if (codigoErroneo = comprobarCodigoMedico()) //Se comprueba si el codigo es correcto
            {
                JOptionPane.showMessageDialog(null, "El codigo de medico tiene que estar entre 70 y 100" ,"Error codigo Medico", JOptionPane.ERROR_MESSAGE);
                campoCodigo.setText("");
            }
            else
            {
               recogerInformacion(); //Recogemos la informacion de los campos (la fecha se recoge con el actionPerformed del jDatePicker)
                try {
                    //Creamos objeto y se lo pasamos a modelo
                    Medico obj = new Medico(Integer.parseInt(codigo),Nif,Integer.parseInt(codigoCompañia),nombre,fechaElegida,Integer.parseInt(precioHora));
                    objetoObtenerDatos.nuevoMedico(obj); //Se llama al metodo de Nuevo Medico
                    cambiarPanel();//cambiamos panel
                } catch (Errores ex) {
                    ex.queError(3); //Lanzamos error de DNI personalizado
                    campoNif.setText("");
                    JOptionPane.showMessageDialog(null, "Error en el DNI" ,"ERROR DNI", JOptionPane.ERROR_MESSAGE);
                    
                }
                establecerImagenPorDefecto(); //Establecemos imagen por defecto
            }
    }//GEN-LAST:event_botonAceptarActionPerformed

    //Metodo para comprobar el codigo de medico
    private Boolean comprobarCodigoMedico()
    {
        boolean bandera = false;
        int numero = (Integer.parseInt(campoCodigo.getText()));
            if (numero < 70 || numero > 100)
                bandera = true;
            else
                bandera = false;
        return bandera;
    }
    
    
    //Metodo para establecer imagen por defecto
    private void establecerImagenPorDefecto()
    {
            String direccion = "src/Imagenes/defecto.png";
            String destino = "src/Imagenes/"+codigo+".png";
           
            try {
                Files.copy(Paths.get(direccion), Paths.get(destino),REPLACE_EXISTING);
            } catch (IOException ex) {
                System.out.println(ex.toString());
            }
    }
    
    
    //Se recoge la imagen con el jDatePicker
    private void jDatePicker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePicker1ActionPerformed
        GregorianCalendar fecha = new GregorianCalendar(jDatePicker1.getModel().getYear(), jDatePicker1.getModel().getMonth(), jDatePicker1.getModel().getDay());
        fechaElegida = fecha.getTime();
    }//GEN-LAST:event_jDatePicker1ActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        cambiarPanel();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    //Metodo para cambiar de panel
    private void cambiarPanel()
    {
        BienvenidaCompañia obj = new BienvenidaCompañia(codigoCompañia);
        
        Principal.cambioDePanel(obj);
    }

  //Metodo para recoger la informacion  
    private void recogerInformacion()
    {
        nombre = campoNombre.getText();
        codigo = campoCodigo.getText();
        Nif = campoNif.getText();
        precioHora = campoPrecioHora.getText();
    }
   //Metodo para comprobar los campos
    private Boolean comprobarCampos()
    {
        boolean bandera = false;
        if (campoNombre.getText().length()== 0 || campoCodigo.getText().length()== 0 || campoNif.getText().length()== 0 || campoPrecioHora.getText().length()== 0 )
            bandera = true;
        else
            bandera=false;
        
        return bandera;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoCompañia;
    private javax.swing.JTextField campoNif;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPrecioHora;
    private org.jdatepicker.JDatePicker jDatePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
